stats = {'fishCaght': 'Fish Caght',
 'playOneMinute': 'Played Time',
 'killedBy': 'Killed By',
 'walkOneCm': 'Walked Meters',
 'jump': 'Jumps',
 'killEntity': 'Killed',
 'seItemseItem': '',
 'mobKills': 'Mob Kills',
 'fallOneCm': 'Falled Meters',
 'entityKilledByentityKilledBy': '',
 'deaths': 'Deaths',
 'leaveGame': 'Leaved Game',
 'killEntitykillEntity': '',
 'minecartOneCm': 'Distance by Minecart',
 'swimOneCm': 'Swamn Distance',
 'boatOneCm': 'Meters by Boat',
 'damageTaken': 'Damage Taken',
 'climbOneCm': 'Climded MEters',
 'flyOneCm': 'Flyed Meters',
 'craftItemcraftItem': '',
 'animalsBred': 'Animals Breded',
 'breakItembreakItem': '',
 'horseOneCm': 'Meters by Horse',
 'mineBlockmineBlock': '',
 'drop': '',
 'damageDealt': 'Damage Dealt',
 'jnkFished': '',
 'playerKills': 'Player Kills',
 'diveOneCm': 'Dived Meters',
 'killEntityBat ' : ' Kill bat',
 'killEntityBlaze' : ' Kill blaze',
 'killEntityCaveSpider' : ' Kill cave spider',
 'killEntityChicken' : ' Kill Chicken',
 'killEntityCow' : ' Kill cow',
 'killEntityCreeper' : ' Kill creeer',
 'killEntityEnderman' : ' Kill enderman',
 'killEntityEntityHorse' : ' Kill Horse',
 'killEntityGhast' : ' Kill ghast',
 'killEntityLavaSlime' : ' Kill lava slime',
 'killEntityPig' : ' Kill pig',
 'killEntityPigZombie' : ' Kill Zombie Pig',
 'killEntitySheep' : ' Kill sheep',
 'killEntitySilverfish' : ' Kill silverfish',
 'killEntitySkeleton' : ' Kill skeleton',
 'killEntitySlime' : ' Kill slime',
 'killEntitySpider' : ' Kill spider',
 'illEntitySquid' : ' Kill squid',
 'killEntityWitch ' : ' Kill witch',
 'killEntityZombie' : ' Kill zombie',
 'entityKilledBySkeleton' : 'Killed by skeleton',
 'entityKilledByZombie' : 'Killed by zombie',
 'entityKilledBySpider' : 'Killed by spider',
 'entityKilledByPigZombie' : 'Killed by PigZombie',
 'entityKilledByWitch' : 'Killed by Witch',
 'entityKilledByCreeper' : 'Killed by Creeper',
 'entityKilledByGhast' : 'Killed by Ghast',
 'entityKilledByEnderman' : 'Killed by Enderman',
 'entityKilledByCaveSpider' : 'Killed by CaveSpider',

}

achievements = {'mineWood': 'Wood Mined',
'buildSword': 'Sword Builded',
'killCow': 'Cow killed',
'buildWorkBench': 'Crafting tables',
'buildHoe': '',
'killEnemy': 'Enemies killed',
'buildFurnace': 'Furnaces Built',
'breedCow': 'Cow Breeded',
'cookFish': '',
'diamonds': 'Diamonds gotten',
'diamondsToYou': 'Diamonds given',
'openInventory': '',
'makeBread': '',
'potion': 'Potions',
'buildPickaxe': '',
'bookcase': 'Book Forged',
'portal': 'Portal travelled',
'blazeRod': 'Blaze Rod Gotten',
'bakeCake': 'Cake Baked',
'exploreAllBiomes': '',
'buildBetterPickaxe': '',
'acquireIron': '',
'enchantments': 'enchantments'}

