stats = {'fishCaght': 'Fish Caght',
 'playOneMinute': 'Played Time',
 'killedBy': 'Killed By',
 'walkOneCm': 'Distance Walked',
 'jump': 'Jumps',
 'killEntity': 'Killed',
 'seItemseItem': '',
 'mobKills': 'Mob Kills',
 'fallOneCm': 'Distance Falled',
 'deaths': 'Deaths',
 'leaveGame': 'Leaved Game',
 'killEntitykillEntity': '',
 'minecartOneCm': 'Distance by Minecart',
 'swimOneCm': 'Swamn Distance',
 'boatOneCm': 'Distance by Boat',
 'damageTaken': 'Damage Taken',
 'climbOneCm': 'Distance Climded',
 'flyOneCm': 'Distance Flyed',
 'craftItemcraftItem': '',
 'animalsBred': 'Animals Breded',
 'breakItembreakItem': '',
 'horseOneCm': 'Distance by Horse',
 'damageDealt': 'Damage Dealt',
 'playerKills': 'Player Kills',
 'diveOneCm': 'Distance Dived',
 'killEntityBat ' : ' Kill bat',
 'killEntityBlaze' : ' Kill blaze',
 'killEntityCaveSpider' : ' Kill cave spider',
 'killEntityChicken' : ' Kill Chicken',
 'killEntityCow' : ' Kill cow',
 'killEntityCreeper' : ' Kill creeer',
 'killEntityEnderman' : ' Kill enderman',
 'killEntityEntityHorse' : ' Kill Horse',
 'killEntityGhast' : ' Kill ghast',
 'killEntityLavaSlime' : ' Kill lava slime',
 'killEntityPig' : ' Kill pig',
 'killEntityPigZombie' : ' Kill Zombie Pig',
 'killEntitySheep' : ' Kill sheep',
 'killEntitySilverfish' : ' Kill silverfish',
 'killEntitySkeleton' : ' Kill skeleton',
 'killEntitySlime' : ' Kill slime',
 'killEntitySpider' : ' Kill spider',
 'killEntitySquid' : ' Kill squid',
 'killEntityWitch ' : ' Kill witch',
 'killEntityZombie' : ' Kill zombie',
 'entityKilledBySkeleton' : 'Killed by skeleton',
 'entityKilledByZombie' : 'Killed by zombie',
 'entityKilledBySpider' : 'Killed by spider',
 'entityKilledByPigZombie' : 'Killed by PigZombie',
 'entityKilledByWitch' : 'Killed by Witch',
 'entityKilledByCreeper' : 'Killed by Creeper',
 'entityKilledByGhast' : 'Killed by Ghast',
 'entityKilledByEnderman' : 'Killed by Enderman',
 'entityKilledByCaveSpider' : 'Killed by CaveSpider',

}


achievements = {'ghast': 'Return to Sender',
'mineWood': 'Getting Wood',
'buildSword': 'Time to Strike!',
'theEnd': 'The End.',
'killCow': 'Cow Tipper',
'buildWorkBench': 'Benchmarking',
'buildHoe': 'Time to Farm!',
'killEnemy': 'Monster Hunter',
'spawnWither': 'The Beginning?',
'buildFurnace': 'Hot Topic',
'breedCow': 'Repopulation',
'cookFish': 'Delicious Fish',
'diamonds': 'DIAMONDS!',
'diamondsToYou': 'Diamonds to you!',
'openInventory': 'Taking Inventory',
'makeBread': 'Bake Bread',
'potion': 'Local Brewery',
'fullBeacon': 'Beaconator',
'buildPickaxe': 'Time to Mine!',
'onARail': 'On A Rail',
'killWither': 'The Beginning.',
'snipeSkeleton': 'Sniper Duel',
'bookcase': 'Librarian',
'blazeRod': 'Into Fire',
'overkill': 'Overkill',
'bakeCake': 'The Lie',
'flyPig': 'When Pigs Fly',
'exploreAllBiomes': 'Adventuring Time',
'buildBetterPickaxe': 'Getting an Upgrade',
'acquireIron': 'Acquire Hardware',
'enchantments': 'Enchanter'}
